### ISSUE TITLE
Error getting this to run :(

### ISSUE THREAD

**Issue by the13fools** [rileyjshaw/virtuoso#1]
/Users/fool/Documents/misc/virtuoso/index.js:22
const fs = require('fs');
^^^^^
SyntaxError: Use of const in strict mode.
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:906:3

when I follow the steps and then run "node index.js"

:(

**Comment by the13fools** [comment]
When I run "node --harmony index.js", I get other syntax errors.

const {parseMidi} = require('midi-file');
      ^
SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)

**Comment by rileyjshaw** [comment]
Which version of node are you using?

```
node --version
```

It won't work on anything below version 6, I'm afraid.

**Comment by the13fools** [comment]
v0.12.7

**Comment by rileyjshaw** [comment]
@the13fools ah, that sounds like the problem then! I just added a note to the README, let me know if it still doesn't work once you've [updated node](https://github.com/creationix/nvm).

Out of curiosity, how'd you come across this project? :)

**Comment by the13fools** [comment]
Came across it on the internet - googling for midi visualization :P.  Doing a hardware project that makes EL materials touch sensitive, and I was looking for something where the triggering was visually obvious.

Ended up using a different visualizer - hopefully will play with running this at some point though!

**Comment by rileyjshaw** [comment]
Ah, sorry this didn't end up working out for you! Your project sounds cool,
hit me up with a link if you put it online! :)
